import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUp, Plus, Settings, MessageSquare, Mic, Square, ShieldCheck, Folder, Cpu, Command, Activity, X, Volume2, Trash2, Check, Orbit} from 'lucide-react';
import './style.css';
import {OllamaModels} from './OllamaModels';
import {LatestOperation} from './operations';

type Chat = {role:string; content:string|null; tool_calls?:unknown[]};
type Session = {id:string; title:string};
type Approval = {confirmation_id:string; call:{name:string;arguments:Record<string,unknown>}};
type Config = {llm_provider:string;llm_model:string;llm_base_url:string;has_api_key:boolean;has_voice_key:boolean;workspace_dir:string;allowed_applications:Record<string,string>;stt_model:string;tts_model:string};
async function api(path:string, options:RequestInit={}) {
 const r=await fetch(path,options);if(!r.ok){let d=await r.json().catch(()=>({detail:r.statusText}));throw new Error(typeof d.detail==='string'?d.detail:'Invalid request');} return r;
}
function App(){
 const [ready,setReady]=useState(false),[token,setToken]=useState(''),[error,setError]=useState('');
 const [sessions,setSessions]=useState<Session[]>([]),[sid,setSid]=useState(''),[messages,setMessages]=useState<Chat[]>([]);
 const [input,setInput]=useState(''),[status,setStatus]=useState('idle'),[connected,setConnected]=useState(false),[approval,setApproval]=useState<Approval|null>(null);
 const [config,setConfig]=useState<Config|null>(null),[settings,setSettings]=useState(false),[key,setKey]=useState(''),[voiceKey,setVoiceKey]=useState(''),[appPaths,setAppPaths]=useState('{}');
 const [activity,setActivity]=useState<{time?:string;type:string;tool?:string;result?:unknown}[]>([]),[showActivity,setShowActivity]=useState(false),[recording,setRecording]=useState(false),[reconnect,setReconnect]=useState(0);
 const ws=useRef<WebSocket|null>(null),recorder=useRef<MediaRecorder|null>(null),bottom=useRef<HTMLDivElement>(null),audio=useRef<HTMLAudioElement|null>(null);
 const [draft,setDraft]=useState<Config|null>(null),[saving,setSaving]=useState(false),[loadingHistory,setLoadingHistory]=useState(false);
 const voice=useRef(new LatestOperation()),historyLoad=useRef(new LatestOperation()),audioUrl=useRef(''),streamRef=useRef<MediaStream|null>(null),recordTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [testing,setTesting]=useState(false),[connectionResult,setConnectionResult]=useState<{ok:boolean;message:string;latency_ms?:number}|null>(null);
 const connectionTest=useRef(new LatestOperation());
 useEffect(()=>{connectionTest.current.cancel();setTesting(false);setConnectionResult(null);},[settings,draft?.llm_provider,draft?.llm_model,draft?.llm_base_url,key]);
 async function testConnection(){if(!draft||testing)return;const op=connectionTest.current.begin();setTesting(true);setConnectionResult(null);try{const result=await (await api('/settings/test-connection',{method:'POST',signal:op.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({llm_provider:draft.llm_provider,llm_model:draft.llm_model,llm_base_url:draft.llm_base_url,...(key?{llm_api_key:key}:{})})})).json();if(op.isCurrent())setConnectionResult(result);}catch(e){if(op.isCurrent())setConnectionResult({ok:false,message:'Connection test could not finish. Check that Orbit is running and try again.'});}finally{if(op.isCurrent())setTesting(false);}}
 const busy=!['idle','error'].includes(status);
 async function refresh(){try{setSessions(await (await api('/sessions')).json());}catch(e){setError(String(e));}}
 async function login(value:string){try{await api('/auth',{method:'POST',headers:{Authorization:'Bearer '+value}});setToken('');setReady(true);setError('');}catch(e){setError(String(e));}}
 useEffect(()=>{const fragment=new URLSearchParams(location.hash.slice(1));const t=fragment.get('token');history.replaceState(null,'',location.pathname);if(t){void login(t);}else{api('/settings').then(()=>setReady(true)).catch(()=>{});}},[]);
 useEffect(()=>{if(ready){void refresh();api('/settings').then(r=>r.json()).then(setConfig).catch(e=>setError(String(e)));}},[ready]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'});},[messages,status]);
 useEffect(()=>{if(!ready||!sid)return;let alive=true;const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws?session_id=${sid}`);ws.current=socket;
 socket.onopen=()=>{if(alive)setConnected(true);};
 socket.onclose=()=>{if(alive){setConnected(false);setStatus('idle');setApproval(null);}};
 socket.onmessage=e=>{if(!alive)return;const event=JSON.parse(e.data);
 if(event.type==='thinking'||event.type==='executing')setStatus(event.type);
 if(event.type==='executing'||event.type==='tool_result')setActivity(prev=>[...prev.slice(-99),event]);
 if(event.type==='confirmation_required'){setApproval(event);setStatus('awaiting approval');}
 if(event.type==='confirmation_expired'){setApproval(null);}
 if(event.type==='completed'){setMessages(prev=>[...prev,{role:'assistant',content:event.content}]);setStatus('idle');setApproval(null);void refresh();}
 if(event.type==='error'||event.type==='cancelled'){setError(event.message);setStatus('idle');setApproval(null);void refresh();}
 };return()=>{alive=false;socket.close();setConnected(false);};},[ready,sid,reconnect]);
 async function select(id:string){if(busy)return;const op=historyLoad.current.begin();ws.current?.close();ws.current=null;setConnected(false);setLoadingHistory(true);setSid(id);setReconnect(n=>n+1);setMessages([]);setError('');setActivity([]);try{const data=await (await api('/sessions/'+id,{signal:op.signal})).json();if(op.isCurrent())setMessages(data);}catch(e){if(op.isCurrent())setError(String(e));}finally{if(op.isCurrent())setLoadingHistory(false);}}
 async function newChat(){try{const d=await (await api('/sessions',{method:'POST'})).json();await refresh();await select(d.session_id);}catch(e){setError(String(e));}}
 function send(){if(!input.trim()||busy||loadingHistory||!connected||ws.current?.readyState!==WebSocket.OPEN)return;ws.current.send(JSON.stringify({type:'message',message:input}));setMessages(p=>[...p,{role:'user',content:input}]);setInput('');setError('');setStatus('thinking');}
 function approve(value:boolean){ws.current?.send(JSON.stringify({type:'confirmation',confirmation_id:approval?.confirmation_id,approved:value}));setApproval(null);setStatus('executing');}
 function openSettings(){setDraft(config?{...config}:null);setAppPaths(JSON.stringify(config?.allowed_applications||{},null,2));setKey('');setVoiceKey('');setError('');setSettings(true);}
 function closeSettings(){if(saving)return;setSettings(false);setDraft(null);setKey('');setVoiceKey('');setError('');}
 async function save(){if(!draft||saving)return;setSaving(true);try{await api('/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({llm_provider:draft.llm_provider,llm_model:draft.llm_model,llm_base_url:draft.llm_base_url,stt_model:draft.stt_model,tts_model:draft.tts_model,workspace_dir:draft.workspace_dir,allowed_applications:JSON.parse(appPaths),...(key?{llm_api_key:key}:{}),...(voiceKey?{voice_api_key:voiceKey}:{})})});setConfig(await (await api('/settings')).json());setSettings(false);setDraft(null);setKey('');setVoiceKey('');setError('');}catch(e){setError(String(e));}finally{setSaving(false);}}
 function releaseVoice(){if(recordTimer.current)clearTimeout(recordTimer.current);recordTimer.current=null;if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop();recorder.current=null;streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;audio.current?.pause();audio.current=null;if(audioUrl.current)URL.revokeObjectURL(audioUrl.current);audioUrl.current='';}
 function cancelVoice(){voice.current.cancel();releaseVoice();setRecording(false);setStatus('idle');}
 useEffect(()=>()=>{voice.current.cancel();historyLoad.current.cancel();connectionTest.current.cancel();releaseVoice();},[]);
 async function speak(text:string){cancelVoice();const op=voice.current.begin();try{setStatus('speaking');const r=await api('/voice/speak',{method:'POST',signal:op.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.slice(0,4000)})});const blob=await r.blob();if(!op.isCurrent())return;const url=URL.createObjectURL(blob);audioUrl.current=url;const a=new Audio(url);audio.current=a;a.onended=()=>{if(op.isCurrent())cancelVoice();};a.onerror=()=>{if(op.isCurrent()){cancelVoice();setError('Audio playback failed');}};await a.play();}catch(e){if(op.isCurrent()){cancelVoice();setError(String(e));}}}
 async function record(){if(recording){recorder.current?.stop();return;}cancelVoice();const op=voice.current.begin();setStatus('listening');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!op.isCurrent()){stream.getTracks().forEach(t=>t.stop());return;}streamRef.current=stream;const r=new MediaRecorder(stream);recorder.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>chunks.push(e.data);r.onerror=()=>{if(op.isCurrent()){cancelVoice();setError('Microphone recording failed');}};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());if(!op.isCurrent())return;if(recordTimer.current)clearTimeout(recordTimer.current);setRecording(false);setStatus('transcribing');try{const form=new FormData();const extension=r.mimeType.includes('mp4')?'mp4':r.mimeType.includes('ogg')?'ogg':'webm';form.append('file',new Blob(chunks,{type:r.mimeType}),'recording.'+extension);const data=await (await api('/voice/transcribe',{method:'POST',body:form,signal:op.signal})).json();if(op.isCurrent())setInput(data.text);}catch(e){if(op.isCurrent())setError(String(e));}finally{if(op.isCurrent())cancelVoice();}};r.start();setRecording(true);recordTimer.current=setTimeout(()=>{if(op.isCurrent()&&r.state==='recording')r.stop();},60000);}catch(e){if(op.isCurrent()){cancelVoice();setError('Microphone unavailable: '+String(e));}}}
 function stop(){if(['speaking','listening','transcribing'].includes(status)){cancelVoice();return;}if(ws.current?.readyState===WebSocket.OPEN)ws.current.send(JSON.stringify({type:'cancel'}));}
 if(!ready)return <div className="login"><Orbit size={44}/><h1>Your desktop. A little smarter.</h1><p>Open the desktop launcher, or enter your local access token.</p><input aria-label="Access token" type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="Local access token"/><button onClick={()=>void login(token)}>Connect to Orbit</button>{error&&<p role="alert">{error}</p>}</div>;
 return <div className="shell"><aside><div className="brand"><Orbit size={29}/><span>orbit<span className="brand-dot">.</span></span><small>DESKTOP</small></div><button className="new" onClick={newChat} disabled={busy}><Plus size={17}/> New conversation <kbd>＋</kbd></button><div className="section-label">YOUR CONVERSATIONS</div><nav>{sessions.length===0&&<p className="muted">A fresh start. Create your first chat.</p>}{sessions.map(s=><div className={'session '+(sid===s.id?'selected':'')} key={s.id}><button disabled={busy} onClick={()=>void select(s.id)}><MessageSquare size={15}/><span>{s.title}</span></button><button aria-label={'Delete '+s.title} disabled={busy} onClick={async()=>{try{await api('/sessions/'+s.id,{method:'DELETE'});if(sid===s.id){historyLoad.current.cancel();ws.current?.close();ws.current=null;setConnected(false);setLoadingHistory(false);setSid('');setMessages([]);}await refresh();}catch(e){setError(String(e));}}}><Trash2 size={13}/></button></div>)}</nav><div className="side-bottom"><div className="workspace"><Folder size={16}/><div><strong>Local workspace</strong><span title={config?.workspace_dir}>{config?.workspace_dir.replaceAll(String.fromCharCode(92),'/').split('/').pop()||'workspace'}</span></div><ShieldCheck size={16}/></div><button onClick={openSettings} disabled={busy}><Settings size={17}/> Settings <span className="version">v0.2</span></button></div></aside>
 <main><header><div><span className="breadcrumb">WORKSPACE</span><span className="slash">/</span><strong>Assistant</strong></div><div className="connection"><i className={connected?'online':''}/>{connected?'Connected':sid?'Disconnected':'Ready'}{sid&&!connected&&<button onClick={()=>setReconnect(n=>n+1)}>Reconnect</button>}<span className="model">{config?.llm_model||'Choose a model'}</span></div></header>
 <div className="chat-scroll">{messages.filter(m=>m.role==='user'||(m.role==='assistant'&&m.content)).length===0?<div className="welcome"><div className="orbit-art"><Orbit size={62}/></div><span className="eyebrow">A LITTLE HELP. A LOT MORE POSSIBLE.</span><h1>What can we do<br/>together today?</h1><p>Think it through. Get it done.<br/>Your assistant for the everyday things on your desktop.</p><div className="suggestions">{[['Know my system','Show my system information',Cpu],['Organize my space','List the files in my workspace',Folder],['Make a fresh start','Create a folder called ideas',Plus]].map(([title,prompt,Icon])=>{const I=Icon as typeof Cpu;return <button key={String(title)} onClick={()=>{setInput(String(prompt));if(!sid)void newChat();}}><I size={21}/><strong>{String(title)}</strong><span>{String(prompt)} ↗</span></button>;})}</div></div>:<div className="messages">{messages.filter(m=>m.role==='user'||(m.role==='assistant'&&m.content)).map((m,i)=><article className={'message '+m.role} key={i}><div className="avatar">{m.role==='user'?'S':<Orbit size={20}/>}</div><div><div className="message-label">{m.role==='user'?'You':'Orbit'}</div><div className="message-text" dir="auto">{m.content}</div>{m.role==='assistant'&&<button className="speak" disabled={busy||!config?.has_voice_key} onClick={()=>void speak(m.content||'')}><Volume2 size={14}/> Listen · AI voice</button>}</div></article>)}</div>}
 {busy&&<div className="working"><span className="pulse"/>{status}…</div>}<div ref={bottom}/></div>
 <div className="compose-area">{error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={14}/></button></div>}{!config?.llm_model&&<div className="setup-note">Choose your model in Settings to start chatting. <button onClick={openSettings}>Open settings ↗</button></div>}<div className="composer"><textarea aria-label="Message" placeholder={sid?'Ask anything, or give your desktop a task…':'Create a conversation to get started…'} value={input} maxLength={16000} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}}}/><div className="composer-toolbar"><span><Command size={14}/> Enter to send · Shift + Enter for a new line</span><div><button title="Record voice (cloud transcription)" aria-label="Record voice" className={recording?'recording':''} disabled={(busy&&!recording)||!config?.has_voice_key} onClick={()=>void record()}>{recording?<Square size={18}/>:<Mic size={19}/>}</button>{busy?<button className="send" aria-label="Stop" onClick={stop}><Square size={17}/></button>:<button className="send" aria-label="Send message" disabled={!connected||loadingHistory||!input.trim()} onClick={send}><ArrowUp size={20}/></button>}</div></div></div><footer><ShieldCheck size={13}/> You're in control. Changes need your approval.<button onClick={async()=>{try{const saved=await (await api('/audit')).json();if(saved.length)setActivity(saved);setShowActivity(true);}catch(e){setError(String(e));}}}><Activity size={13}/> Activity</button></footer></div></main>
 {approval&&<div className="overlay"><section className="modal approval" role="dialog" aria-modal="true" aria-label="Approve operation"><ShieldCheck size={30}/><h2>Your permission, please.</h2><p>Review this operation before Orbit runs it on your computer.</p><strong>{approval.call.name}</strong><pre>{JSON.stringify(approval.call.arguments,null,2)}</pre><div className="actions"><button onClick={()=>approve(false)}>Deny</button><button className="primary" onClick={()=>approve(true)}><Check size={16}/> Approve once</button></div></section></div>}
 {settings&&draft&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="Settings"><button className="close" aria-label="Close settings" onClick={closeSettings}><X/></button><span className="eyebrow">MAKE IT YOURS</span><h2>Assistant settings</h2><p>Model requests go to your selected provider. Voice uses OpenAI.</p><label>Provider<select value={draft.llm_provider} onChange={e=>setDraft({...draft,llm_provider:e.target.value,llm_base_url:''})}><option value="ollama">Ollama · local model</option><option value="openai">OpenAI · cloud model</option></select></label>{draft.llm_provider==='ollama'&&<OllamaModels key={draft.llm_base_url} baseUrl={draft.llm_base_url} value={draft.llm_model} onSelect={name=>setDraft({...draft,llm_model:name})}/>}<label>Model name<input value={draft.llm_model} placeholder="Your installed or API model name" onChange={e=>setDraft({...draft,llm_model:e.target.value})}/></label><label>Base URL (optional)<input value={draft.llm_base_url} placeholder="Use provider default" onChange={e=>setDraft({...draft,llm_base_url:e.target.value})}/></label><label>Model API key {draft.has_api_key?'· saved':''}<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Leave blank to keep existing key"/></label><div className="connection-test"><button disabled={testing||saving} onClick={()=>void testConnection()}>{testing?'Testing connection…':'Test connection'}</button><small>Tests the values above without saving. Sends a short model request; cloud usage may be billed. Allow up to 30 seconds.</small>{connectionResult&&<div className={connectionResult.ok?'test-success':'test-failure'} role="status"><strong>{connectionResult.ok?'Connection successful':'Connection failed'}</strong><p>{connectionResult.message}</p>{connectionResult.latency_ms!==undefined&&<small>Response time: {(connectionResult.latency_ms/1000).toFixed(2)} s</small>}</div>}</div><label>Voice API key {draft.has_voice_key?'· available':''}<input type="password" value={voiceKey} onChange={e=>setVoiceKey(e.target.value)} placeholder="Optional separate OpenAI key"/></label><label>Workspace folder<input value={draft.workspace_dir} onChange={e=>setDraft({...draft,workspace_dir:e.target.value})}/></label><label>Allowed applications (JSON alias → full .exe path)<textarea value={appPaths} onChange={e=>setAppPaths(e.target.value)} /></label><small>Keys stay on this computer in your user settings file. Audio is sent to OpenAI only when you use voice.</small>{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button onClick={closeSettings}>Cancel</button><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save settings'}</button></div></section></div>}
 {showActivity&&<div className="overlay"><section className="modal activity"><button className="close" aria-label="Close activity" onClick={()=>setShowActivity(false)}><X/></button><h2>Activity</h2><p>Completed operations are not undone when a request is stopped.</p>{activity.length===0?<p>No operations recorded yet.</p>:activity.map((e,i)=><pre key={i}>{JSON.stringify(e,null,2)}</pre>)}</section></div>}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
